services:
  httpd:
    image: httpd:latest
    container_name: httpd
    ports:
      - "8080:80"
    #volumes:
    #  - ./html:/usr/local/apache2/htdocs/
    restart: unless-stopped
    networks:
      - httpd

  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: setup
    user: "0"
    command: >
      bash -c '
      echo "Waiting for Elasticsearch availability";
      until curl -s http://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
      echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:changeme" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"changeme\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    networks:
      - siem

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=changeme
      - xpack.security.http.ssl.enabled=false
    restart: unless-stopped
    networks:
      - siem
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
      #- SERVER_PUBLICBASEURL=http://localhost:5601
    restart: unless-stopped
    networks:
      - siem

networks:
  httpd:
    external: true
  siem:
    external: true